### ISSUE TITLE
Add Visualization Entity and Charts

### ISSUE THREAD

**Issue by federicca** [NuCivic/data-openFDA#11]
As a Portal Admin I want to create custom charts and visualizations around my data that i can later embed internally and externally.

**Comment by jonpugh** [comment]
on the way

**Comment by jonpugh** [comment]
dependencies on the way...

**Comment by jonpugh** [comment]
Done, enabled on live.

**Comment by federicca** [comment]
can't create charts, maybe some components are missing?

![screen shot 2015-06-29 at 18 10 45](https://cloud.githubusercontent.com/assets/1379537/8419749/399a6d48-1e8a-11e5-81f7-316dc0d1e736.png)

After I add a csv i should be able to define the variables but the fields aren't showing up, neither is the "next" button

**Comment by jonpugh** [comment]
ah, i see now there are extra steps... 1 moment.

**Comment by jonpugh** [comment]
I added all the modules and libraries yesterday.
