### ISSUE TITLE
Figure out how to get Aarons recline API into the dkan site

### ISSUE THREAD

**Issue by jonpugh** [NuCivic/data-openFDA#13]
@acouch wrote an awesome chartbuilder for recline.  

http://nucivic.github.io/openfda.js/examples/

How do we get it into our DKAN site?  We can update dkan in our site if we have to, just need some advice!

Thanks!

**Comment by acouch** [comment]
# Steps

### Select Endpoint

Enforcement ones are easiest.
<img width="1183" alt="screen shot 2015-07-06 at 12 07 50 pm" src="https://cloud.githubusercontent.com/assets/512243/8528306/efd4ec1c-23d7-11e5-8311-2d9957ff3da4.png">

### Filter

The "Query count" will change the fields to `term` and `count`. This is the easiest to visualize. City and stater are good.

You can also search on a specific field.
<img width="1218" alt="screen shot 2015-07-06 at 12 08 24 pm" src="https://cloud.githubusercontent.com/assets/512243/8528311/f58df16c-23d7-11e5-9196-cad5e3f6a39b.png">

### Select Items to graph

<img width="1202" alt="screen shot 2015-07-06 at 12 08 32 pm" src="https://cloud.githubusercontent.com/assets/512243/8528364/2f5593aa-23d8-11e5-9a90-7d050592165c.png">

### Select and update graph

Just keep clicking "Next"

### Grab iframe code and embed in Drupal page or Block

<img width="1179" alt="screen shot 2015-07-06 at 12 12 51 pm" src="https://cloud.githubusercontent.com/assets/512243/8528393/62d7777a-23d8-11e5-98d5-c49faa32dfc5.png">

**Comment by acouch** [comment]
Example: http://openfda.nucivic.build/listeria-outbreaks-state

**Comment by jonpugh** [comment]
This is good.

I've embedded the chart maker itself into our site: http://openfda.nucivic.build/create-chart

Perhaps this is good enough for now.  I don't know if we will have more time to update dkan to the latest release and incorporate this new chart builder more directly.

**Comment by jonpugh** [comment]
@acouch When you get a chance, could you outline the alternative integration you mentioned this afternoon?

Is there functionality related to this in the new release of DKAN?

**Comment by jonpugh** [comment]
I've merged the recline project into this repo.

It's now available at http://openfda.nucivic.build/openfda.js/examples/index.html

**Comment by jonpugh** [comment]
I think we can call this one fixed.  No time left to do anything more interesting.
