### ISSUE TITLE
Collected Feedback

### ISSUE THREAD

**Issue by jonpugh** [NuCivic/data-openFDA#20]
We demoed the site to @andrewhoppin and determined that the Datasets page isn't good enough.  It currently shows just the same paragraph and a link to the OpenFDA datasets page.

In order to make it more interesting, we need to be able to create charts.  @acouch finished the nucivic/openfda.js recline backend, so we can create charts.

Let's create an interesting chart for each dataset at least.

**Comment by andrewhoppin** [comment]
See also https://github.com/NuCivic/data-openFDA/issues/23

**Comment by andrewhoppin** [comment]
@rar624 @Rallah and Fig Leaf folks have been invited to create interesting charts that could then be embedded.

**Comment by andrewhoppin** [comment]
From Jared Shapiro: 

"My initial impressions are that there is some cool stuff there and I do not know what to do with it.  I will explain more after some more hunting and clicking."

I suggest that improved home page content and /About page would help.
