### ISSUE TITLE
Datasets not showing

### ISSUE THREAD

**Issue by rar624** [NuCivic/data-openFDA#21]
http://openfda.nucivic.build/dataset/drugs-labeling/resource/98394bee-e8ba-4a9c-b664-bd46fb12ca52

All the of examples just have links to APIs so they're not showing the ability to demo data.

**Comment by andrewhoppin** [comment]
Thanks @rar624.  This should be addressed as we add more Charts in the next 12 hours; see https://github.com/NuCivic/data-openFDA/issues/23
